// <auto-generated />
using System;
using ArcheryAlley.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArcheryAlley.Migrations
{
    [DbContext(typeof(ArcheryAlleyDBContext))]
    [Migration("20240916120833_Roles_Secured")]
    partial class Roles_Secured
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArcheryAlley.Models.BookingSlots", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotId"));

                    b.Property<TimeSpan>("SlotEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("SlotStartTime")
                        .HasColumnType("time");

                    b.HasKey("SlotId");

                    b.ToTable("BookingSlots");
                });

            modelBuilder.Entity("ArcheryAlley.Models.Reservations", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReservedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservedOn")
                        .HasColumnType("datetime");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("ReservationId");

                    b.HasIndex("ReservedBy");

                    b.HasIndex("SlotId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ArcheryAlley.Models.Roles", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"));

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("1478523690");

                    b.Property<bool>("RoleType")
                        .HasColumnType("bit");

                    b.HasKey("EmpId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ArcheryAlley.Models.Reservations", b =>
                {
                    b.HasOne("ArcheryAlley.Models.Roles", "Role")
                        .WithMany("Reservations")
                        .HasForeignKey("ReservedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Reservations_Roles");

                    b.HasOne("ArcheryAlley.Models.BookingSlots", "Slot")
                        .WithMany("Reservations")
                        .HasForeignKey("SlotId")
                        .IsRequired()
                        .HasConstraintName("FK_Reservations_BookingSlots");

                    b.Navigation("Role");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("ArcheryAlley.Models.BookingSlots", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("ArcheryAlley.Models.Roles", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
